### ISSUE TITLE
"related" items are not being replicated onto "connected" items

### ISSUE THREAD

**Issue by jketreno** [Board-Explorer/board-viewer#11]
If you activate [J5 on the D2000](https://board-explorer.github.io/board-explorer/#quark_mcu_dev_kit_d2000/J5), it shows all of it's related items:

![image](https://user-images.githubusercontent.com/742584/27665569-d28b7498-5c22-11e7-9f28-81ac248f4636.png)

However, it doesn't show the items which are connected to the related items.

For example, **J3 Pin 6** is related to **J5** (which is shown above). **J3 Pin 6** is also connected to **J8 Pin 7**.

If you click on **J3 Pin 6** you see those relationships:

![image](https://user-images.githubusercontent.com/742584/27665648-32b3188a-5c23-11e7-957d-0239837b9fff.png)

I think the problem might be that "related" isn't being copied to all "connected" pins (J8 Pin 7 should have all the same relations as J3 Pin 6) This could be handled either by adding all of that data to the pin's "related" and "connected" lists, or through business logic in board-viewer when it highlights / selects items.

I am thinking selecting any item in the related/connected view result in the same set of items always being selected, regardless of what item is actively clicked on.

@juliocri Thoughts?

**Comment by juliocri** [comment]
@jketreno I was separating the logic for related and connected, currently mixing connected and related in the same steps...

**Comment by jketreno** [comment]
It works now!  :+1: Here is what it looks like if you click on J5 :)

![image](https://user-images.githubusercontent.com/742584/27750857-889df53c-5d8e-11e7-9160-5a6f882a68c1.png)
