### ISSUE TITLE
All components should have default empty values for all arrays

### ISSUE THREAD

**Issue by jketreno** [Board-Explorer/board-viewer#14]
To remove the chance of undefined references and having to check for values being set, eg., `item.keywords`, all *expected* fields should be initialized in items when the boards.json data is loaded.

**Comment by juliocri** [comment]
@jketreno I was reviewing the functionality in board-viewer and I could not detect errors or warnings related with not initialized vars, further than the console error when a keyword is selected and the markdown file for additional info does not exist...

I sent a PR for the board-explorer: https://github.com/Board-Explorer/board-explorer/pull/65
that basically replaces the console error with a warning, I see cleaner the console with this movement! do you think is ok? or is better have only a log, or is better launching the 404 errors as we have now?

**Comment by jketreno** [comment]
Merged and pushed as part of board-explorer.

**Comment by jketreno** [comment]
The change you made needs to occur farther down the code sequence. Instead of being performed in the initial check for `item.html` being set (which is there to use documentation that had already been downloaded) the change to set the content to a string should be in the `return resolve({status: 400});` line.

```javascript
    getDocumentation: function(item, type) {
      return new Promise(function(resolve, reject) {
        if (item.html) {
          return resolve({
            status: 200,
            content: item.html
          });
        }

        this.$.boardViewer.getDocumentation(item.refdes, type, function(results) {
          if (!results || results.error) {
            if (results.status == 400) {
              return resolve({status: 400});
            }
            return reject(new Error(results.error));
          }

          return resolve(results);
        });
      }.bind(this));
    },
```

**Comment by jketreno** [comment]
Nevermind about the prior comment... not sure if we are fixing something fixable.

Are you referring to messages like:

![image](https://user-images.githubusercontent.com/742584/35945011-95036dfa-0c13-11e8-8827-1483f0d32b86.png)

when you try and load things like [J22Pin3](https://board-explorer.github.io/board-explorer/#quark_mcu_dev_kit_d2000/J22Pin3) ?
