### ISSUE TITLE
Touch screen is not clearing selected/hover/highlight correctly

### ISSUE THREAD

**Issue by jketreno** [Board-Explorer/board-viewer#17]
If you use a touch screen to interact with the board-viewer, it does not clear out the prior selection/highlight when you tap a new item.

This is likely being caused by the mouseover/mouseout/mousetap on tap events vs. actual mouse events. This could require the API between board-explorer and board-viewer to change.

**Comment by jketreno** [comment]
On Chrome, using the Device Toolbar (CTRL-SHIFT-J to enable Developer Tools, then CTRL-SHIFT - M to toggle the device toolbar) you can simulate the touch events using a mouse pointer device.

**Comment by juliocri** [comment]
@jketreno if you select a component the hover is not being cleaned up after you touch to dismiss the current selection, the hover remains present in the component and the button. - This Only happens now in IE 11 with a touch screen device.

**Comment by jketreno** [comment]
Gah! I wonder what series of events IE sends when emulating mouse events via touch? The code still has the console.log() messages in onTap, onFilterTap, onFilterOver, and onFilterOut -- can you paste the console log of events you see when you tap on items?

**Comment by juliocri** [comment]
It seems that in IE touching the screen causes a _onFilterOver at the beginning.

selecting a component:

_onFilterOver
_onFilterTap

deselecting:

_onTap

**Comment by juliocri** [comment]
@jketreno I was doing some test directly on a windows local environment in order to discover the root cause, seems that regardless the extra call to ''_onSelectedChanged'' the problem is only the typo in the remove filter ''highlight-'' (latest commit) so, updating the reference of the board-viewer in the board-explorer bower.json file to update to the latest commit it will be all... could you verify in order to close this issue?

**Comment by jketreno** [comment]
I tagged a new board-viewer, updated board-explorer to depend on that version (0.0.33), and pushed the latest to the gh-pages:

    https://board-explorer.github.io/board-explorer

I had to tell IE to discard the network cache for it to load the new version of the file... once I did that and verified it was pulling the latest version from the site, it worked.

Thanks,
James
