### ISSUE TITLE
Add ability for "categories" to include keywords

### ISSUE THREAD

**Issue by jketreno** [Board-Explorer/board-viewer#3]
If a category list includes a keyword, selecting that category should add that keyword to the filter.

Maybe this should be a new filter type for `addCategory`--eg:

```javascript
foo =  boardViewer.getCategories();
boardViewer.addFilter("randomname", foo[0]);
```

In board-viewer::addFilter, if typeof match === object then it would create a match object of type: category and set the pattern to the category provided. board-viewer::_populateFilter() would then be modified to support adding category items into the filter list.

What do you think?

**Comment by juliocri** [comment]
only for a better understanding of this, that means if a category array contains a keyword within (for mention a random example, below):

``` "list": [ "ACCEL", "J7", "jumper", "gnd" ] ```

selecting this category, filter buttons for components and keyword must to be display?

**Comment by jketreno** [comment]
Yes -- everything in the group "jumper" would be selected.

Expanding your example more (so we can refer back to this issue). Assume the quark_mcu_dev_kit_d2000's board.json file has:

```json
{ "categories": [ {
  "name": "Test category",
  "list": [ "ACCEL", "J7", "JUMPER", "GND" ]
} ] }
```

If the user selects that category, the visual result should be the same as if the user had visited the URL with the following parameters:

[#quark_mcu_dev_kit_d2000/ACCEL,J7,JUMPER,GND](https://board-explorer.github.io/board-explorer/#quark_mcu_dev_kit_d2000/ACCEL,J7,JUMPER,GND)

For consistency, once a category is defined, the user should be able to pass a category name via the URL. I filed issue #5 to track that feature addition.

**Comment by juliocri** [comment]
I think we currently add categories and its keyword for example, and following the example above:

```
boardViewer.addFilter("randomname", {"type": "LIST", "set": foo[0].list});
```

**Comment by juliocri** [comment]
review the case for keywords.

**Comment by juliocri** [comment]
Categories already accept keywords but only if in the .json are in upper case.

**Comment by jketreno** [comment]
Merged and online as of September :)
