### ISSUE TITLE
Max the "size to view" icon cycle between "zoom to fit selected" and "zoom all" if items are selected

### ISSUE THREAD

**Issue by jketreno** [Board-Explorer/board-viewer#32]
Clicking the "size to view" icon should cycle between zooming the viewport to fit the outlined items and zooming to the full view of the board.

This will allow mobile users to select items and more easily see all the items that have been highlighted as related.

The zoomed viewport should be centered to the bounding box of all the items and scaled such that the bounding box is 80% the size of the viewport (similar to how the board is sized when the button is tapped.)

**Comment by jketreno** [comment]
For example, if the user has selected [J8PIN2 and VBAT](https://board-explorer.github.io/board-explorer/#quark_mcu_dev_kit_d2000/J8PIN2,VBAT), and had manually zoomed in and panned around, they might see this:

![image](https://user-images.githubusercontent.com/742584/31914134-5d1f395a-b7fe-11e7-90dc-1b82a19bb8b5.png) 

On first tap of the ![image](https://user-images.githubusercontent.com/742584/31914167-817b6134-b7fe-11e7-9ec5-aa7500f3a2ab.png) icon it would "zoom to fit" the selected items:

![image](https://user-images.githubusercontent.com/742584/31914256-cde91ec6-b7fe-11e7-876f-224b1033dca5.png)

If the user doesn't manually change the zoom or pan position, then clicking the zoom button again would zoom to fit the entire board:

![image](https://user-images.githubusercontent.com/742584/31914238-bdcd4c06-b7fe-11e7-825f-2e3cec185b48.png)

**Comment by jketreno** [comment]
In case it is useful, here's a snippet I was playing with for getting the bounding rectangle of all the active filter items. I put this code in the _zoomToFit function in board-viewer.html:

```javascript
    var rect = null, items = this.querySelectorAll("#filters div");

    Array.prototype.forEach.call(items, function(el) {
      var tmp = el.getBoundingClientRect();
      if (rect == null) {
        rect = {
          left: tmp.left,
          right: tmp.right,
          top: tmp.top,
          bottom: tmp.bottom
        };
      } else {
        if (tmp.left < rect.left) {
          rect.left = tmp.left;
        }
        if (tmp.right > rect.right) {
          rect.right = tmp.right;
        }
        if (tmp.top < rect.top) {
          rect.top = tmp.top;
        }
        if (tmp.bottom > rect.bottom) {
          rect.bottom = tmp.bottom;
        }
      }
    });

    console.log("Bounding rectangle: " + JSON.stringify(rect, null, 2));
```

**Comment by jketreno** [comment]
Adding the following to the above will set this.zoom to the (possibly) correct value to zoom the window, based purely on the **width**. The code needs to determine the zoom based on the width and height and then select the smaller of the two zoom levels to use.

Setting the translation value should be similar; find the center of the bounding rect, then apply the inverse of the current scale, then apply the new scale to the value.

```javascript
    console.log("Bounding rectangle: " + JSON.stringify(rect, null, 2));

    var targetWidth = ((rect.right - rect.left) / (this.scale + this.scale * this.zoom)) / 0.8;
    this.zoom = (this.clientWidth / targetWidth - this.scale) / this.scale;
    this.resize();
    return;
```

**Comment by jketreno** [comment]
I just tested with a check for height as well... seems to scale correctly. The translation offsets still need to be figured out though.

Below is the full snippet I injected into _zoomToFit:

```javascript
    var rect = null, items = this.querySelectorAll("#filters div");

    Array.prototype.forEach.call(items, function(el) {
      var tmp = el.getBoundingClientRect();
      if (rect == null) {
        rect = {
          left: tmp.left,
          right: tmp.right,
          top: tmp.top,
          bottom: tmp.bottom
        };
      } else {
        if (tmp.left < rect.left) {
          rect.left = tmp.left;
        }
        if (tmp.right > rect.right) {
          rect.right = tmp.right;
        }
        if (tmp.top < rect.top) {
          rect.top = tmp.top;
        }
        if (tmp.bottom > rect.bottom) {
          rect.bottom = tmp.bottom;
        }
      }
    }.bind(this));

    console.log("Bounding rectangle: " + JSON.stringify(rect, null, 2));

    var targetWidth = ((rect.right - rect.left) / (this.scale + this.scale * this.zoom)) / 0.8,
      targetHeight = ((rect.bottom - rect.top) / (this.scale + this.scale * this.zoom)) / 0.8;
    this.zoom = Math.min((this.clientWidth / targetWidth - this.scale) / this.scale,
        (this.clientHeight / targetHeight - this.scale) / this.scale);
    this.resize();
    return;
```

**Comment by jketreno** [comment]
FYI, I just pushed a fix for #42 to correct the selection clearing while zooming.

**Comment by jketreno** [comment]
The zoom slider bar should set itself based on the calculated zoom level; if the level is beyond the extents the user can move the slider, the slider would limit to those extents. If the user then interacts with the slider, the zoom level is then set based on how the user interacts.

If you add the following just before the return in the prior snippet, the functionality of the zoom slider seems to behave like I'm expecting:

```javascript
    this.$$('#zoomControl').value = Math.max(Math.min(this.zoom, 2.0), 0);
```
The only time this interaction is jarring is if the user has zoomed in on a single item, which can result in a very high `zoom` level. If they then interact with the zoom slider, the first step is a big jump when it clamps the active zoom level into the [0,2] range.

**Comment by jketreno** [comment]
@juliocri With the latest changes to how zoom works (commit 696ce86f), the snippet in the last comment would now be something like:

```javascript
this.$$('#zoomControl').value = Math.max(Math.min(this.scale, this.maxScale), this.minScale);
```

**Comment by juliocri** [comment]
@jketreno finally there is a branch with the functional sample #44

**Comment by juliocri** [comment]
@jketreno I think I will need assistance with the branch 'fix-32', testing it with the latest changes ( 696ce86) it does not work, I think I will need to restructure the functions according to the new logic...

**Comment by jketreno** [comment]
@juliocri I've pushed a new version to master (in v0.0.44) which now toggles between 'zoom to fit selection' and 'zoom to fit board.' Can you create a patch to add your icon changes based on the `this.zoomedToFit` variable?

There are some interaction quirks on initialization; sometimes the zoom icon does the wrong thing on first tap, or after the user has moved the board around / resized. I haven't had a chance to debug it at all, or to reliably reproduce it. If you can play with it and see if you encounter any odd behavior, and file any issues with what you find (or patches if you find fixes) that would be **great** :)
