### ISSUE TITLE
"connected" is not recursing to all connected pins

### ISSUE THREAD

**Issue by jketreno** [Board-Explorer/board-viewer#8]
In D2000, J8 Pin 9 in the BoosterPack is connected to J3 Pin 10 and J23 Pin 6.

In the board.json file, this is declared by J3Pin10 including a "connected" reference to J8Pin9. J23Pin6 also includes a "connected" reference to J8Pin9.

J8Pin9 appears to have it's "connected" being configured correctly--hovering over it yields the other two connections:

![image](https://user-images.githubusercontent.com/742584/27406046-95ede088-5688-11e7-8ce9-de95cd8086b5.png)

However, if you hover over J23Pin6, the connection to J3Pin10 is not shown:

![image](https://user-images.githubusercontent.com/742584/27406193-006a1788-5689-11e7-960e-74b15d4f8bb9.png)

After board.json is loaded, J23Pin6's "connected" should include "J8Pin9" and "J3Pin10".

**Comment by juliocri** [comment]
@jketreno the fix for this is now available as PR: https://github.com/Board-Explorer/board-viewer/pull/10

**Comment by jketreno** [comment]
Merged, and verified. Closing.
